GET http://localhost:3000/books

###
GET http://localhost:3000/books/2

###
POST http://localhost:3000/books
Content-Type: application/json


{
    "title":  "Algorightms and Data Structure in Java",
    "isbn": "965-895-12",
    "publishedDate": "12/28/1999",
    "author": "Josey Wales"
}


###
DELETE http://localhost:3000/books/5

###
PUT http://localhost:3000/books/5
Content-Type: application/json

{
     "title":  "Algorightms and Data Structure in Java",
    "isbn": "965-000-12",
    "publishedDate": "12/28/1999",
    "author": "Josey Wales"
}